import{i as a,S as l}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();document.getElementById("search-form");document.getElementById("search-input");document.getElementById("gallery");document.querySelector("container");const m={method:"GET"},u="45147494-75a7f96365cbfb286af0bc26b",c="https://pixabay.com/api/?";async function f(n){try{const o=new URLSearchParams({key:u,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0});console.log(":"+c+o);const t=await fetch(c+o,m).then();return t===""?(a.info("Sorry, there are no images matching your search query. Please try again!"),{total:0,totalHits:0,hits:[]}):await t.json()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}return null}const d=document.getElementById("gallery"),y=new l("#gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function g(n){const o=n.map(t=>`
      <a href="${t.largeImageURL}" class="container">
        <img src="${t.webformatURL}" alt="${t.tags}">
        <div class="info">
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </a>
    `).join("");d.innerHTML=o,y.refresh()}const h=document.getElementById("search-form");document.getElementById("search-input");const p=document.getElementById("gallery");document.querySelector("container");h.addEventListener("submit",w);async function w(n){var s;n.preventDefault();const t=n.currentTarget.elements["search-input"].value.trim().toLowerCase();if(t===""){a.error({title:"Error",message:"Search field cannot be empty!"});return}p.innerHTML="",a.info({title:"Loading",message:"Searching for images..."});try{const e=await f(t);((s=e==null?void 0:e.hits)==null?void 0:s.length)>0?g(e.hits):a.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"})}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}}
//# sourceMappingURL=commonHelpers.js.map
